[build-system]
requires = [
    "setuptools>=64",
    "wheel"
]
# Use legacy backend to import local packages in setup.py
build-backend = "setuptools.build_meta:__legacy__"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements/requirements.txt"]}

[project.optional-dependencies]
dev = {file = ["requirements/requirements-dev.txt"]}
