name: CPU

on:
  push:
    branches:
      - 'master'
      - 'staging**'
  pull_request:
    branches:
      '**'

jobs:

  # basic install and cpu-only tests
  unit-tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: environment
        run: |
          which python
          python --version

      - name: Install MII
        run: |
          pip install .[dev,local]

      - name: Unit tests
        run: |
          cd tests
          pytest --color=yes --durations=0 --verbose -m "CPU" ./
