name: Formatting

on:
  workflow_dispatch:
  pull_request:
    branches:
      '**'
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # formatting and basic install on cpu-only machine
  formatting:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: environment
        run: |
          which python
          python --version

      - name: Install dependencies
        run: |
          grep -E "clang-format|pre-commit" requirements/requirements-dev.txt | xargs pip install

      - name: Formatting checks
        run: |
           pre-commit run --all-files
